version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
environment:
    matrix:
    - solution_folder: 1.Introduction/Introduction
      full_project_name: Introduction.csproj
      
    - solution_folder: 3.BasicInfo/BasicInfo
      full_project_name: BasicInfo.csproj 
    
    - solution_folder: 3.BasicInfo/BasicInfo
      full_project_name: SimpleDiExample.csproj

    - solution_folder: 4.Model/Infestation
      full_project_name: Infestation.csproj

before_build: nuget restore %solution_folder%
build: 
    project: '%full_project_name%'
    publish_wap: true