version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
environment:
    matrix:
    - project_folder: 1.Introduction/Introduction
      project_name: Introduction.csproj
      
    - project_folder: 3.BasicInfo/BasicInfo
      project_name: BasicInfo.csproj 
    
    - project_folder: 3.BasicInfo/SimpleDiExample
      project_name: SimpleDiExample.csproj

    - project_folder: 4.Model/Infestation/Infestation
      project_name: Infestation.csproj

before_build: nuget restore %project_folder%
build: 
    project: '%project_folder%/%project_name%'
    publish_wap: true